env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - '@typescript-eslint'
rules: {
  "linebreak-style": 0,
  "indent": ["error", 2], 
  "no-console": ["error", { allow: ["warn", "error", "log"] }],
  "@typescript-eslint/no-use-before-define": ["off"]
}
